### ISSUE TITLE
[bug] Tests that pass JSX to stories fail when using with @swc/jest

### ISSUE THREAD

**Issue by chris-barry-rs** [storybookjs/jest#44]
**Describe the bug**
When using the transform `"\\.[jt]sx?$": ["@swc/jest"],`, tests will fail with the error 
```
  ● Test suite failed to run

    TypeError: expect.extend: `default` is not a valid matcher. Must be a function, is "object"

      23 | export const MixedAvatarStack: StoryObj<typeof AvatarStack> = {
      24 |   args: {
    > 25 |     children: [
         |               ^
      26 |       <Tooltip content="Avatar 1" size="mini" key="avatar1">
      27 |         <Avatar
      28 |           size="mini"

      at node_modules/@storybook/expect/dist/index.js:1:132825
          at Array.forEach (<anonymous>)
      at t.setMatchers (node_modules/@storybook/expect/dist/index.js:1:132769)
      at Function.v.extend (node_modules/@storybook/expect/dist/index.js:1:130549)
      at Object.<anonymous> (node_modules/@storybook/jest/dist/index.js:409:8)
      at Object.<anonymous> (src/components/AvatarStack/AvatarStack.stories.tsx:25:15)
      at Object.<anonymous> (src/components/AvatarStack/__tests__/avatarStack.test.tsx:7:69)
```

This can be resolved by adding 
```js
const validMatchers = { ...matchers };
Object.keys(validMatchers).forEach((matcherName) => {
  const matcher = validMatchers[matcherName];
  if (typeof matcher === 'undefined' || typeof matcher === 'boolean') {
    delete validMatchers[matcherName];
  }
});
delete validMatchers.default
```

to `node_modules/@storybook/jest/dist/index.js`. This works correctly in `@storybook/jest@0.1.0`

For reference, my `.swcrc` file is
```json
{
  "jsc": {
    "transform": { "react": { "runtime": "automatic" } }
  }
}
```

**To Reproduce**
1. Configure jest with the transform `"\\.[jt]sx?$": "@swc/jest",`
2. Create a storybook test using composeStories from `@storybook/react`, the story will need to have an arg that is a JSX element and a play function, e.g.
```js
export const Accordion: StoryObj<typeof AccordionComponent> = {
  args: {
    children: <p>Accordion Content</p>,
  },
 play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    const accordionHeader = canvas.getByText("Accordion Content");

    await expect(accordionHeader).toBeInTheDocument();
  }
}
```
4. Run the test
5. See error

**Expected behavior**

**Screenshots**

**System**
```
  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.17.1 - ~/.volta/tools/image/node/18.17.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.1.0 - ~/.volta/tools/image/npm/10.1.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 17.0
  npmPackages:
    @storybook/addon-actions: 7.4.1 => 7.4.1
    @storybook/addon-designs: 7.0.5 => 7.0.5
    @storybook/addon-essentials: 7.4.1 => 7.4.1
    @storybook/addon-interactions: 7.4.1 => 7.4.1
    @storybook/addon-links: 7.4.1 => 7.4.1
    @storybook/addon-mdx-gfm: 7.4.1 => 7.4.1
    @storybook/jest: 0.2.2 => 0.2.2
    @storybook/mdx2-csf: 1.1.0 => 1.1.0
    @storybook/react: 7.4.1 => 7.4.1
    @storybook/react-vite: 7.4.1 => 7.4.1
    @storybook/test-runner: 0.13.0 => 0.13.0
    @storybook/testing-library: 0.2.0 => 0.2.0
    "@swc/core": "1.3.84",
    "@swc/jest": "0.2.29",
    "@testing-library/jest-dom": "6.1.3",
    "@testing-library/react": "14.0.0",
    "@testing-library/user-event": "14.4.3",
    "jest": "29.7.0",
    "jest-environment-jsdom": "29.7.0",
```

**Additional context**

**Comment by ChrisW-B** [comment]
fixed in v0.2.3!
